import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";
const setup=fs.readFileSync(new URL("../../scripts/local/setup-windows.ps1",import.meta.url),"utf8");
const smoke=fs.readFileSync(new URL("../../scripts/local/check-hive.ps1",import.meta.url),"utf8");
const projectList=fs.readFileSync(new URL("../../scripts/local/hive-project-list.ps1",import.meta.url),"utf8");
const assertions=fs.readFileSync(new URL("../../scripts/local/hive-smoke-assertions.ps1",import.meta.url),"utf8");
test("windows pins exact GEF and HIVE and refuses mismatch",()=>{assert.match(setup,/866fe3af8cccc65c929aaf6a47a924401fa448b3/);assert.match(setup,/52bd3dab54dd4f16264072e198ed1fc23168f7fa/);assert.match(setup,/Pinned-Commit/);assert.match(setup,/HIVE_ENV_ROOT_CONFLICT/)});
test("never performs destructive Docker volume wipe",()=>{assert.doesNotMatch(setup,/down\s+--volumes|down\s+-v|Remove-Item.*HiveData/i)});
test("HIVE smoke actually tests READY and retrieval; semantic optional and gated",()=>{for(const s of ["READY","/retrieval/lexical","/retrieval/hybrid","/retrieval/semantic","SEMANTIC_PROVIDER_NOT_CONFIGURED","$project.project_id","$($index.error)"])assert(smoke.includes(s));assert.equal((smoke.match(/Convert-HiveProjectList -Response \$projectResponse/g)||[]).length,2);assert(projectList.includes("foreach($item in $Response)"));assert(!smoke.includes('Invoke-RestMethod -Uri "$BaseUrl/api/v1/projects" -Method Get -TimeoutSec 10 | Where-Object'))});

test("R8 retrieval proofs reject empty arrays and semantic fallback",()=>{for(const s of ["Assert-HiveResultSet -Response $lexical","Assert-HiveResultSet -Response $hybrid","Assert-HiveResultSet -Response $result","Assert-HiveSemanticContribution -Response $hybrid","CORPUS_EMPTY_OR_NO_REPOSITORY_REFERENCES","SEMANTIC_EMBEDDINGS_INCOMPLETE_OR_STALE","strict_semantic=$true"])assert(smoke.includes(s));assert(!smoke.includes("@($lexical.results).Count"));assert(!smoke.includes("@($hybrid.results).Count"));assert(!smoke.includes("@($result.results).Count"));for(const s of ["$null -eq $Response.results","source_content_sha256","chunk_content_sha256","semantic_contribution"])assert(assertions.includes(s))});
